### ISSUE TITLE
Welcome, how are you

### ISSUE THREAD

**Issue by loithoo** [SampleOrganisationESU/SampleRepositoryESU#6]
**Is your feature request related to a problem? Please describe.**
I would like a welcome page

**Describe the solution you'd like**
I would like the application to display "Welcome, how are you?".

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by loithoo** [comment]
# [As a Business Analyst:]

## Feature description
On access, the application displays a welcome message.

## Time
It shouldn't take more than 10 mins

## Version
It's on the way for 1.4.4

**Comment by loithoo** [comment]
# [As a PM]
Ok lets start with this please. Make it quick!

**Comment by loithoo** [comment]
# [As Support]
Ok it seems to work on acceptance

**Comment by loithoo** [comment]
# [As BA]
Perfect, I updated :
* specifications
* release notes

**Comment by topce** [comment]
it is done
